#!/bin/bash
#
# Bootstraps your world. Checks to see if dependencies are met, and then
# installs them if they aren't.

set -e

echo ''
echo '' > /tmp/play-bootstrap

info() {
  printf "  [    ] $1"
}

success() {
  printf "\r  [ ok ] $1           \n"
}

fail() {
  printf "\r  [FAIL] $1           \n"
  echo ''
  echo 'See /tmp/play-bootstrap for more information.'
  exit
}

if test -f "config/play.yml"
then
  success 'config loaded'
else
  . script/setup
  success 'config loaded'
fi

# Install our system dependencies.
if [ $(uname -s) = "Darwin" ]
then
  . script/setup.osx
elif [ $(uname -s) = "Linux" ]
then
  if test $(which apt-get)
  then
    . script/setup.apt
  fi
fi

# bundler
info 'bundler'
if test $(which bundle)
then
  success 'bundler'
else
  gem install bundler > /tmp/play-bootstrap
  success 'bundler'
fi

# gems
info 'gems'
if bundle install --binstubs --path vendor/gems >> /tmp/play-bootstrap
then
  success 'gems'
else
  fail 'gems'
fi

# Create database. Assume root user and blank password. If this doesn't work,
# tell them to do it manually.
info 'setting up mysql'

[ $MYSQL_USER ] && user=$MYSQL_USER || user='root'
[ $MYSQL_PASSWORD ] && password=$MYSQL_PASSWORD || password=''

if mysql -u $user --password="$password" -e 'USE play' >> /tmp/play-bootstrap 2>&1
then
  success 'mysql database ready'
else
  if mysql -u $user --password="$password" -e 'CREATE DATABASE IF NOT EXISTS play CHARACTER SET utf8 COLLATE utf8_unicode_ci;' >> /tmp/play-bootstrap 2>&1
  then
    success 'created mysql database'
  else
    echo "We assume MySQL credentials of root and a blank password. If that's not the case, run script/bootstrap with MYSQL_USER and MYSQL_PASSWORD environment variables set." >> /tmp/play-bootstrap
    fail 'could not create mysql database'
  fi
fi

info 'data migrations'
if bundle exec rake db:migrate >> /tmp/play-bootstrap 2>&1
then
  success 'data migrated'
else
  fail 'problem migrating data'
fi

info 'caching album art'
if script/cache-art >> /tmp/play-bootstrap 2>&1
then
  success 'album art cached'
else
  fail 'problem caching album art'
fi

echo ""
echo "  You're all set!"
