#!/bin/sh
#
# Bootstraps your world. Checks to see if dependencies are met, and then
# installs them if they aren't.

set -e

echo ''
echo '' > /tmp/play-bootstrap

info() {
  printf "  [    ] $1"
}

success() {
  printf "\r  [ ok ] $1           \n"
}

fail() {
  printf "\r  [FAIL] $1           \n"
  echo ''
  echo 'See /tmp/play-bootstrap for more information.'
  exit
}

brew_installed() {
  brew list | grep -i $1 > /dev/null
  [ $? -eq 0 ]
}

# Installs a dependency with Homebrew
brew_install() {
  if brew_installed $1
  then
    success $1
    return
  fi

  info "installing $1"
  if $2 >> /tmp/play-bootstrap
  then
    brew install $1 >> /tmp/play-bootstrap
    success $1
  else
    fail $1
  fi
}

# brew
if test $(which brew)
then
  success 'homebrew'
else
  ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)" > /tmp/play-bootstrap
  success 'homebrew'
fi

brew_install 'mysql'
brew_install 'taglib'
brew_install 'media-info'
brew_install 'mpd'
brew_install 'mpc'

# bundler
info 'bundler'
if test $(which bundle)
then
  success 'bundler'
else
  gem install bundler > /tmp/play-bootstrap
  success 'bundler'
fi

# gems
info 'gems'
if bundle install --binstubs --path vendor/gems > /tmp/play-bootstrap
then
  success 'gems'
else
  fail 'gems'
fi

echo ""
echo "  You're all set!"