#!/usr/bin/env ruby
#
# Caches all of the album art locally so we can muck around with it.
#
# This should only need to be run once, on installation. If you add songs
# using the web interface, we'll cache those songs right then and there. If
# you add songs outside of Play, or if you run into anything fishy, feel free
# to run this task multiple times- it won't hurt anything.

require './config/environment'

paths = Play.client.listall
puts "Caching art for #{paths.count} songs..."

FileUtils.mkdir_p 'public/images/art'

count = 0
paths.each do |path|
  result = Song.new(:path => path).cache_album_art
  count += 1 if result
end

puts "Done! #{count} songs updated."
