#!/usr/bin/env ruby
#
# Manages your queue for you. This is a long-running process that prunes songs
# we've already played from the playlist and adds interesting songs to the
# queue so the music ain't ever stop.

require './config/environment'

loop do
  if Play.default_channel.queue.size < 2
    song = Song.new(:path => Play.mpd.files[:file].sample)
    Play.default_channel.add(song, nil)
    Play.mpd.clearerror
  end
  sleep 1
end
