#!/usr/bin/env ruby
#
# Manages your queue for you. This is a long-running process that prunes songs
# we've already played from the playlist and adds interesting songs to the
# queue so the music ain't ever stop.

require './config/environment'

loop do
  Channel.all.each do |channel|
    if channel.queue.size < 2

      if channel.song_plays.manually_queued.count > 50
        # this channel has some history, queue from the past
        song = channel.song_plays.manually_queued.sample.song
      else
        # this is new, queue from the library
        song = Song.new(:path => Play.library.files[:file].sample)
      end

      channel.add(song, nil)
      channel.mpd.clearerror
    end
  end
  sleep 1
end
