#!/usr/bin/env ruby
#
# Manages your queue for you. This is a long-running process that prunes songs
# we've already played from the playlist and adds interesting songs to the
# queue so the music ain't ever stop.

require './app/play'

$client = Play::Client.new

job = fork do
  loop do
    if Play::Queue.songs.size < 2
      song = Play::Song.new($client.listall.sample)
      Play::Queue.add(song,nil)
    end
    sleep 1
  end
end

Process.detach(job)
