#!/bin/sh
#
# Handles recording of system audio.
#
# $1 - The function to perform. Possible values:
#      start - Starts recording.
#      stop  - Stops recording.
# $2 - The name to append to the recording. Possibly a username. Only required
#      for stopping.
#
# Examples:
#
#   record start
#   record stop github-dj-holman

if test "$1" = "start"
then
  osascript << APPLESCRIPT
  tell application "QuickTime Player"
      activate
      set recording to new audio recording
      start recording
  end tell
APPLESCRIPT
else
  osascript << APPLESCRIPT
  tell application "QuickTime Player"
      activate
      stop document 1
  end tell
APPLESCRIPT

  # Sleep so QuickTime doesn't get confused
  sleep 5

  # Import recording
  filename="$2-$(date +%Y-%m-%d_%H%M%S)"
  mv "$HOME/Movies/Audio Recording.m4a" "$HOME/Movies/$filename.m4a"
  script/add-to-itunes "$HOME/Movies/$filename.m4a"
  rm -rf "$HOME/Movies/$filename.m4a"

  # Close out
  osascript << APPLESCRIPT
  tell application "QuickTime Player"
      activate
      close document 1
  end tell
APPLESCRIPT
fi