#!/bin/sh
#
# Reports on the status of the stack.
set -e

echo ""

if test "$(ps aux | grep "mpd config/mpd" | grep -v grep)"
then
  echo "  [ ok ] music"
else
  echo "  [down] music"
  echo "         run \`script/music start\`"
fi

if test "$(ps aux | grep "queue" | grep -v grep)"
then
  echo "  [ ok ] queue"
else
  echo "  [down] queue"
  echo "         run \`script/queue\`"
fi

# Change from `thin server` whenever we figure out deployment
if test "$(ps aux | grep thin | grep -v grep)"
then
  echo "  [ ok ] web"
else
  echo "  [down] web"
  echo "         run \`script/web start\`"
fi
