#!/bin/sh
#
# Reports on the status of the stack.
set -e

echo ""

if test "$(ps aux | grep "mpd config/mpd" | grep -v grep)"
then
  echo "  [ ok ] music"
else
  echo "  [down] music"
  echo "         run \`script/music start\`"
fi

# Change from `rackup` whenever we figure out deployment
if test "$(ps aux | grep "rackup" | grep -v grep)"
then
  echo "  [ ok ] web"
else
  echo "  [down] web"
  echo "         run \`script/web start\`"
fi