#!/bin/sh

set -e
[ -z "$DEBUG" ] || set -x

export RAILS_ROOT=$(cd "$(dirname $0)"/.. && pwd)

echo "===> Running tests..."
ruby -I test \
  -e "(ARGV.empty? ? Dir['${RAILS_ROOT}/test/**/*_test.rb'] : ARGV).each { |f| load f }"
