#!/bin/sh
#
# Updates the existing Play to the current version. Currently just a simple
# git pull (but may run migrations and assorted fun later).

echo "- Updating Play"
git pull --quiet

echo "- Updating libraries"
bundle install --quiet