#!/bin/sh
#
# Start the web server

case "$1" in
  start )
    bundle exec unicorn -c config/unicorn.rb
    ;;
  stop )
    if [ -f /tmp/play/web.pid ]
    then
      kill `cat /tmp/play/web.pid`
      rm -rf /tmp/play/web.pid
    fi
    ;;
esac
