#!/bin/sh
#
# Start the web server

case "$1" in
  start )
    if [ "$RAILS_ENV" == "production" ]
    then
      bundle exec unicorn -D -c config/unicorn.rb
    else
      bundle exec unicorn -c config/unicorn.rb
    fi
    ;;
  stop )
    pkill unicorn
    rm -f tmp/pids/unicorn.pid
    ;;
esac
